FROM registry.cn-beijing.aliyuncs.com/modoso/transformersx-large:latest
#Why not pull all docker files into a folder? Because the building in Aliyun has some problem.

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models" \
      version="1.0.0"

WORKDIR /app/transformersx

RUN rm -rf *

# Copy as early as possible so we can cache ...
COPY . .

RUN pip install -r requirements.txt --no-cache-dir


RUN rm -rf log && mkdir log && python ai_transformersx.down_tasks.py --cache-dir /app/models --task-name download_models --model-size large


