FROM registry.cn-beijing.aliyuncs.com/aimogo/transformers:latest

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models" \
      version="1.0.0"

RUN apt-get clean && apt-get update --fix-missing
RUN apt-get install -y --fix-missing --no-install-recommends \
  build-essential && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  mkdir /app

WORKDIR /app

RUN rm -rf *

# Copy as early as possible so we can cache ...
COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

RUN python down_tasks.py --task_name distil

VOLUME ["/app"]

