version: 1
formatters:
  simple:
    format: '[%(asctime)s][P%(process)d-T%(thread)d-%(threadName)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  pretrain_file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log/pretraining.log
    maxBytes: 256000000
    backupCount: 5
  data_file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log/data.log
    maxBytes: 256000000
    backupCount: 5
  finetune_file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log/finetuning.log
    maxBytes: 256000000
    backupCount: 5
  task_file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log/task.log
    maxBytes: 256000000
    backupCount: 5
loggers:
  data:
    level: INFO
    handlers: [console,pretrain_file]
    propagate: no
  pretrain:
    level: INFO
    handlers: [console,pretrain_file]
    propagate: no
  finetune:
    level: INFO
    handlers: [console,finetune_file]
    propagate: no
  task:
    level: INFO
    handlers: [console,task_file]
    propagate: no
root:
  level: WARN
  handlers: [console]