FROM registry.cn-beijing.aliyuncs.com/modoso/transformersx-large:latest

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models" \
      version="1.0.0"

WORKDIR /app/transformersx

RUN rm -rf *

# Copy as early as possible so we can cache ...
COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

RUN rm -rf log && mkdir log && python down_tasks.py --cache-dir /app/models --task-name download_models --task-size large


