#FROM nvcr.io/nvidia/pytorch:19.06-py3
#registry.cn-beijing.aliyuncs.com/aimonvidia/pytorch_19_06 is same with nvcr.io/nvidia/pytorch:19.06-py3
#FROM registry.cn-beijing.aliyuncs.com/aimonvidia/pytorch_19_06
FROM registry.cn-beijing.aliyuncs.com/aimonvidia/pytorch_20_03
ARG PIP="pip install -i https://pypi.douban.com/simple/"

RUN $PIP python-box boltons tqdm==4.45.0
# For the package update frequently
RUN $PIP transformers==2.10.0
# For my package
RUN pip install --no-cache-dir ai-harness==0.4.11 ai-transformersx==0.4.18

WORKDIR /workspace