FROM registry.cn-beijing.aliyuncs.com/modoso/transformersx-base:latest
#Why not pull all docker files into a folder? Because the building in Aliyun has some problem.

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models--Roberta" \
      version="1.0.0"

WORKDIR /app/transformersx

RUN rm -rf log && mkdir log && python down_tasks.py --cache-dir /app/models --models=roberta



