FROM registry.cn-beijing.aliyuncs.com/modoso/transformersx-base:latest
#Why not pull all docker files into a folder? Because the building in Aliyun has some problem.

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models--AlBert" \
      version="1.0.0"

WORKDIR /app/transformersx

RUN rm -rf log && mkdir log

RUN pip install --no-cache-dir \
    pytorch_lightning==0.7.6 \
    ai-harness==0.4.12 \
    ai-transformersx==0.4.22

#    MODELS = {
#        "cn": [bert_model("clue/albert_chinese_tiny"),
#               bert_model("clue/albert_chinese_small"),
#               default_model("onePatient/albert_chinese_small"),
#               bert_model("voidful/albert_chinese_tiny"),
#               bert_model("voidful/albert_chinese_small"),
#               bert_model("voidful/albert_chinese_base"),
#               bert_model("voidful/albert_chinese_large"),
#               bert_model("voidful/albert_chinese_xlarge")
#               ]}
#
#  Split the download of the models for the docker build cache.

ARG RUN_CMD_CN="python down_tasks.py --cache-dir /app/models --language=cn --model_type=albert"

RUN $RUN_CMD_CN --model_path="clue/albert_chinese_tiny"
RUN $RUN_CMD_CN --model_path="clue/albert_chinese_small"
RUN $RUN_CMD_CN --model_path="onePatient/albert_chinese_small"
RUN $RUN_CMD_CN --model_path="voidful/albert_chinese_tiny"
RUN $RUN_CMD_CN --model_path="voidful/albert_chinese_small"
RUN $RUN_CMD_CN --model_path="voidful/albert_chinese_base"
RUN $RUN_CMD_CN --model_path="voidful/albert_chinese_large"
RUN $RUN_CMD_CN --model_path="voidful/albert_chinese_xlarge"


