FROM registry.cn-beijing.aliyuncs.com/aimonvidia/transformers-all

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models" \
      version="1.0.0"

RUN mkdir -p /app/transformersx && mkdir /app/models

WORKDIR /app/transformersx

RUN rm -rf *

# Copy as early as possible so we can cache ...
COPY . .

RUN pip install --no-cache-dir \
    ai-harness==0.4.11 \
    python-box==4.2.2  \
    boltons==20.0.0    \
    transformers==2.11.0  \
    ai-transformersx==0.4.20 \


