FROM registry.cn-beijing.aliyuncs.com/aimonvidia/transformers-all

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models" \
      version="1.0.0"

RUN mkdir -p /app/transformersx && mkdir /app/models

WORKDIR /app/transformersx

RUN rm -rf *

# Copy as early as possible so we can cache ...
COPY . .

RUN pip install -r requirements.txt --no-cache-dir
