FROM registry.cn-beijing.aliyuncs.com/modoso/transformersx-base:latest
#Why not pull all docker files into a folder? Because the building in Aliyun has some problem.

LABEL maintainer="Dongsong.Mo" \
      name="Docker for download the transformer pretrain models--Electra" \
      version="1.0.0"

WORKDIR /app/transformersx
RUN rm -rf log && mkdir log

RUN pip install --no-cache-dir \
    pytorch_lightning==0.7.6 \
    ai-harness==0.4.12 \
    ai-transformersx==0.4.22

#    MODELS = {
#        "cn": [default_model("hfl/chinese-electra-small-discriminator"),
#               default_model("hfl/chinese-electra-small-generator"),
#               default_model("hfl/chinese-electra-base-discriminator"),
#               default_model("hfl/chinese-electra-base-generator"),
#               default_model("hfl/chinese-electra-large-discriminator"),
#               default_model("hfl/chinese-electra-large-generator")
#               ]}
#
#  Split the download of the models for the docker build cache.

ARG RUN_CMD_CN="python down_tasks.py --cache-dir /app/models --language=cn --model_type=electra"

RUN $RUN_CMD_CN --model_path="hfl/chinese-electra-small-discriminator"
RUN $RUN_CMD_CN --model_path="hfl/chinese-electra-small-generator"
RUN $RUN_CMD_CN --model_path="hfl/chinese-electra-base-discriminator"
RUN $RUN_CMD_CN --model_path="hfl/chinese-electra-base-generator"
RUN $RUN_CMD_CN --model_path="hfl/chinese-electra-large-discriminator"
RUN $RUN_CMD_CN --model_path="hfl/chinese-electra-large-generator"




